<Project>
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>
    <Authors>7Bpencil</Authors>
    <Copyright>Copyright (c) 7Bpencil 2026</Copyright>
    <AssemblyVersion>1.16.1</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Version>$(AssemblyVersion)</Version>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <SPTPath>..\..\..\..</SPTPath>
    <AssemblySearchPaths>
      $(AssemblySearchPaths);
      $(SPTPath)\EscapeFromTarkov_Data\Managed;
      $(SPTPath)\BepInEx\core;
      $(SPTPath)\BepInEx\plugins\spt;
      $(SPTPath)\BepInEx\plugins\Fika;
    </AssemblySearchPaths>
  </PropertyGroup>
</Project>
