<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Shared.props" />

  <PropertyGroup>
    <AssemblyName>7Bpencil.MaterialEditor.Fika</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaterialEditor\MaterialEditor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\..\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\..\..\..\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Fika.Core">
      <HintPath>..\..\..\..\BepInEx\plugins\Fika\Fika.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="CopyToSPT" AfterTargets="AfterBuild">
    <PropertyGroup>
      <OutDir>$(ProjectDir)..\..\..\..\BepInEx\plugins\7Bpencil.WeaponCamoAndStickers</OutDir>
    </PropertyGroup>
    <Exec Command="mkdir &quot;$(OutDir)&quot;" ContinueOnError="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(OutDir)" />
  </Target>

  <Target Name="CopyToSPT" AfterTargets="AfterBuild" Condition="'$(Configuration)'=='Release'">
    <PropertyGroup>
      <OutDir>$(ProjectDir)..\..\Stage\BepInEx\plugins\7Bpencil.WeaponCamoAndStickers</OutDir>
    </PropertyGroup>
    <Exec Command="mkdir &quot;$(OutDir)&quot;" ContinueOnError="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(OutDir)" />
  </Target>

</Project>
